### ISSUE TITLE
Meta-Issue to track overall Progress of the Repo.

### ISSUE THREAD

**Issue by Translucent504** [panacloud-modern-global-apps/serverless-solutions-patterns-cdk#5]
# End Goal:
Implement the following patterns from the [CDK Patterns Website](https://cdkpatterns.com/patterns/all/)

## Progress:

- [x] [The Big Fan](https://github.com/cdk-patterns/serverless/blob/master/the-big-fan/README.md)  Assigned: #1 
- [x] [Destined Lambda](https://github.com/cdk-patterns/serverless/blob/master/the-destined-lambda/README.md) Assigned: #2 
- [x] [Eventbridge ATM](https://github.com/cdk-patterns/serverless/blob/master/the-eventbridge-atm/README.md) Assigned: #3 
- [ ] [State Machine](https://github.com/cdk-patterns/serverless/blob/master/the-state-machine/README.md) Assigned: #4 
- [x] [Eventbridge ETL](https://github.com/cdk-patterns/serverless/blob/master/the-eventbridge-etl/README.md) Assigned: #6 
- [x] [Scalable Webook](https://github.com/cdk-patterns/serverless/blob/master/the-scalable-webhook/README.md) Assigned #7 
- [x] [S3 React Website](https://github.com/cdk-patterns/serverless/blob/master/s3-react-website/README.md) Assigned #8 

- [x] [Saga Stepfunction](https://github.com/cdk-patterns/serverless/blob/master/the-saga-stepfunction/README.md) Assigned #9 

- [x] [Eventbridge Circuit Breaker](https://github.com/cdk-patterns/serverless/blob/master/the-eventbridge-circuit-breaker/README.md) Assigned #10 

- [x] [Dynamo Streamer](https://github.com/cdk-patterns/serverless/blob/master/the-dynamo-streamer/README.md) Assigned #11 
- [ ] [WAF API Gateway](https://github.com/cdk-patterns/serverless/blob/master/the-waf-apigateway/README.md) 
- [ ] [Lambda Trilogy](https://github.com/cdk-patterns/serverless/blob/master/the-lambda-trilogy/README.md)

- [ ] [Cloudwatch Dashboard](https://github.com/cdk-patterns/serverless/blob/master/the-cloudwatch-dashboard/README.md)
- [ ] [Scheduled Lambda](https://github.com/cdk-patterns/serverless/blob/master/the-scheduled-lambda/README.md)

- [ ] [Xray Tracer](https://github.com/cdk-patterns/serverless/blob/master/the-xray-tracer/README.md)
- [ ] [Simple Webservice](https://github.com/cdk-patterns/serverless/blob/master/the-simple-webservice/README.md)
